 name: Telegram Notify
 
 on: push
 
 jobs:
  notify1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my codes
        uses: actions/checkout@v2
        run: echo Hi!
      
      - name: Telegram Notification to Self
        uses: appleboy/telegram-action@0.0.3
            with:
              to: ${{ secrets.TELEGRAM_TO }}
              token: ${{ secrets.TELEGRAM_TOKEN }}
              args: ${{ github.event_name }} event triggered.
        
