 name: Telegram Notify
 
 on: push
 
 jobs:
  notify1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my codes
        uses: actions/checkout@master
      
      - name: Telegram Notification to Self
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ github.event_name }} event triggered.
        
