 name: Telegram Notification
 
 on: [push]
 
 jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notify - New Realease in GitHub
            uses: appleboy/telegram-action@0.0.3
            with:
              to: ${{ secrets.TELEGRAM_TO }}
              token: ${{ secrets.TELEGRAM_TOKEN }}
              args: ${{ github.event_name }} event triggered.
